builders:
  ack_generator:
    import: "package:ack_generator/builder.dart"
    builder_factories: ["ackGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude:
          - "**/*.ack.dart"
          - "**/*.ack.g.dart"

  ack_models:
    import: "package:ack_generator/builder.dart"
    builder_factories: ["ackModelBuilder"]
    build_extensions: {".dart": [".ack.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before:
      - ack_generator|ack_model_json
    applies_builders:
      - ack_generator|ack_model_json
    defaults:
      generate_for:
        exclude:
          - "**/*.ack.dart"
          - "**/*.ack.g.dart"

  ack_model_json:
    import: "package:ack_generator/builder.dart"
    builder_factories: ["ackModelJsonBuilder"]
    build_extensions: {".dart": [".ack.g.dart"]}
    auto_apply: none
    build_to: source
    required_inputs: [".ack.dart"]
