builders:
  ack_generator:
    import: "package:ack_generator/builder.dart"
    builder_factories: ["ackGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
