name: ack_annotations
description: AckType annotation for immutable Ack model generation
version: 1.1.0
repository: https://github.com/conceptadev/ack
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  json_annotation: ^4.12.0
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.15
