name: Publish standard_schema to pub.dev

on:
  push:
    tags:
      # Stable tags, e.g. standard_schema-v1.2.3
      - 'standard_schema-v[0-9]*.[0-9]*.[0-9]*'
      # Pre-release tags, e.g. standard_schema-v0.0.1-dev.1
      - 'standard_schema-v[0-9]*.[0-9]*.[0-9]*-*'

jobs:
  publish:
    uses: btwld/dart-actions/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      packages_folder_path: "packages"
      packages: standard_schema
